### ISSUE TITLE
running in enclave got "/bin/sh: /myapp: not found" error

### ISSUE THREAD

**Issue by raindust** [awslabs/aws-nitro-enclaves-cose#18]
Hi, all. 
I have tested successfully in nitro enclave according to [was developing-applications-linux sample](https://docs.aws.amazon.com/zh_cn/enclaves/latest/user/developing-applications-linux.html).
But after I added this crate as a dependency of my cargo project and add simple code as follows:
```rust
let cose = COSESign1::from_bytes(vec![].as_slice())?;
```
then I re-compiled to execution file and re-build it into docker image, enclave app run failed to like the following:
```
Action: Enclave Console
  Subactions:
    Failed to retrieve enclave CID
    Failed to connect to enclave process
    Failed to connect to specific enclave process: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  Root error file: src/enclave_proc_comm.rs
  Root error line: 129
```
I think this error is caused by the lack of "openssl-dev" library, but even if I add `RUN apk add pkgconfig openssl-dev` to install the package in docker, the same error occurred.

Can someone tell me how to fix this?

**Comment by petreeftime** [comment]
Hi @raindust. The error in the title: `/bin/sh: /myapp: not found` would rather indicate that the file `/myapp` which CMD in the Dockerfile calls doesn't exist. Is it correctly copied in the container?

Other than that, you can check if your binary has any external dependencies by running `ldd ./myapp` locally and see if it requires anything else. If it's compiled with `cargo build --target=x86_64-unknown-linux-musl` then the answer is likely not. If does depend on openssl (libssl, libcrypto), then you can specify that it should be statically linked with `OPENSSL_STATIC=1`:  `OPENSSL_STATIC=1 cargo build --target=x86_64-unknown-linux-musl`.

**Comment by raindust** [comment]
Hi @petreeftime. Thanks for the reply.
I have fixed this error by add "vendored" feature for openssl dependency like this: https://github.com/awslabs/aws-nitro-enclaves-cose/pull/19 .

I modified the openssl dependency because I thought the app that only built with MUSL (and based with the "alpine" Linux distribution when build docker image) can work in the AWS nitro enclave, I did test a docker image that based on ubuntu distribution build app without MUSL and test failed. 
But in your response it seems like MUSL is not the only choice to develop nitro enclave app,  so can you give me a link to introduce nitro enclave supported platforms? I have read [the nitro official document](https://docs.aws.amazon.com/enclaves/latest/user/nitro-enclave.html) and github repos about nitro, but can not find any clue.

**Comment by petreeftime** [comment]
There aren't any specific requirements for the container application, except that it has to define a valid CMD. We recommend Amazon Linux, since it's easier for us to support, but as long as the container works in Docker it should work in a Nitro Enclave and we are using Amazon Linux, Ubuntu, Alpine and nothing (i.e. `FROM scratch`).

**Comment by raindust** [comment]
>..., except that it has to define a valid CMD...

Ok, so I guess my failed enclave app is because there are some invalid access operations (such as network, disk, /etc/random... those are forbidden in nitro enclave), and this is the specific meaning of "valid CMD" you mentioned before. Am I right?

**Comment by petreeftime** [comment]
By valid CMD just means a commandline parameter defined in the Dockerfiles that exists and is executable. If the docker container itself starts, the Nitro Enclave should start as well. The Nitro Enclave itself doesn't define what is a "valid program" in any way. It just runs a Virtual Machine with Linux Kernel and starts a Docker container in this VM. If the program contained tries to do an operation which doesn't work for whatever reason, the program needs to define what happens in such case.

Example:
```
FROM ubuntu
COPY myapp.sh /myapp.sh
CMD [ "/bin/sh", "/myapp.sh" ]
```

**Comment by petreeftime** [comment]
I'll add a Dockerfile example to the samples repo that should help clarify the build.

**Comment by raindust** [comment]
I see, thanks:)
