### ISSUE TITLE
Can Attestation Documents be verified using this ?

### ISSUE THREAD

**Issue by nitish-at** [awslabs/aws-nitro-enclaves-cose#37]
Can we use the functions provided here to validate an attestation document when implementing an own Attestation service ?

***
It can be useful if  README.md could expand more on the ways this repo can be used/ purpose it seves.

**Comment by petreeftime** [comment]
Yes. The process to do this explained more in detail here: https://github.com/aws/aws-nitro-enclaves-nsm-api/blob/main/docs/attestation_process.md#3-attestation-document-validation.
