### ISSUE TITLE
Failed to parse NSM attestation document as `CoseSign1`

### ISSUE THREAD

**Issue by raindust** [awslabs/aws-nitro-enclaves-cose#47]
First I request an attestation document like https://github.com/aws/aws-nitro-enclaves-nsm-api/blob/main/nsm-test/src/bin/nsm-check.rs#L344-L360 into the variable `document`.

Then if I try to parse the `document` like the following:
```rust
        use aws_nitro_enclaves_cose::CoseSign1;

        fn try_get_cose_sign(document: &[u8]) -> Option<CoseSign1> {
		if let Ok(cose) = CoseSign1::from_bytes(document) {
			debug!("CoseSign1 is untagged");
			return Some(cose);
		}
		if let Ok(cose) = CoseSign1::from_bytes_tagged(document) {
			debug!("CoseSign1 is tagged");
			return Some(cose);
		}
		None
	}
```
if I call `try_get_cose_sign` the result is `None` (the same logic worked about 1 year ago)

**Comment by raindust** [comment]
By the way, I used to parse [AttestationDoc](https://github.com/aws/aws-nitro-enclaves-nsm-api/blob/main/src/api/mod.rs#L211) use the `try_get_cose_sign` method mentioned above like:
```rust
                use aws_nitro_enclaves_cose::crypto::Openssl;
                use aws_nitro_enclaves_nsm_api::api::AttestationDoc;

                let cose = try_get_cose_sign(document).unwrap();
		let payload = cose.get_payload::<Openssl>(None)?;
		let doc = AttestationDoc::from_binary(payload.as_slice())?;
```

Is the rest of the parsing logic still working?

**Comment by petreeftime** [comment]
I'll take a look, it should still be working pretty much the same.

**Comment by raindust** [comment]
> First I request an attestation document like https://github.com/aws/aws-nitro-enclaves-nsm-api/blob/main/nsm-test/src/bin/nsm-check.rs#L344-L360 into the variable `document`.
> 
> Then if I try to parse the `document` like the following:
> 
> ```rust
>         use aws_nitro_enclaves_cose::CoseSign1;
> 
>         fn try_get_cose_sign(document: &[u8]) -> Option<CoseSign1> {
> 		if let Ok(cose) = CoseSign1::from_bytes(document) {
> 			debug!("CoseSign1 is untagged");
> 			return Some(cose);
> 		}
> 		if let Ok(cose) = CoseSign1::from_bytes_tagged(document) {
> 			debug!("CoseSign1 is tagged");
> 			return Some(cose);
> 		}
> 		None
> 	}
> ```
> 
> if I call `try_get_cose_sign` the result is `None` (the same logic worked about 1 year ago)

It's a bug in my app that wrapped the `document` and didn't unwrap it after transferring, sorry about that, and thanks for your attention.
